/**
 * Possible statuses for agent tasks
 */
export enum TaskStatus {
  PENDING = 'pending',
  PROCESSING = 'processing',
  COMPLETED = 'completed',
  FAILED = 'failed'
}

/**
 * Interface for an agent task
 */
export interface AgentTask {
  id: string;
  agentType: string;
  input: any;
  output?: any;
  status: TaskStatus;
  createdAt: Date;
  updatedAt: Date;
  completedAt?: Date;
}

/**
 * Interface for results generated by the book summary agent
 */
export interface BookSummaryResult {
  bookTitle: string;
  bookAuthor: string;
  summary: string;
  keyPoints: string[];
  flashcards: {
    question: string;
    answer: string;
  }[];
}

/**
 * Interface for RAG search results
 */
export interface RAGQueryResult {
  query: string;
  response: string;
  sources: {
    noteId: string;
    title: string;
    relevanceScore: number;
  }[];
} 